enum MorselTip: String, CaseIterable {
  case drinkWater = "Drinking a glass of water can kill a craving before it starts."
  case brushTeeth = "Brushing your teeth can make snacking feel weird. Use it!"
  case delayCraving = "Wait 10 minutes before acting on a craving — it often fades."
  case breatheDeep = "Take three deep breaths before grabbing a snack."
  case walkItOff = "A short walk can reset your brain and kill a craving."
  case distractYourself = "Distraction works. Try a game, a book, or texting a friend."
  case hydrateFirst = "You're probably just thirsty. Have water first."
  case chewGum = "Chewing gum tricks your brain into thinking you’re already eating."
  case snackSwap = "Swap sweets for fruit. It satisfies the sweet tooth and adds fibre."
  case journal = "Write it down. Often just naming the craving gives you control."

  case protein = "Protein keeps you full longer. Make it a habit."
  case sleepMatters = "Lack of sleep spikes hunger. Get your rest."
  case mindfulBite = "Eat one bite slowly. Then stop. You’ll be amazed."
  case moveBody = "A little movement clears the mind — and resets the craving."
  case smellFood = "Smell it. You don’t always need to eat it."
  case snackOnPurpose = "If you’re gonna snack, do it mindfully and with intention."
  case planTreats = "Plan treats. Surprises = less control."
  case shopSmart = "Don’t bring it in the house. You can’t eat what’s not there."
  case nightTime = "Evening cravings hit hard. Have a strategy before 8pm."
  case stressSnack = "Notice if you’re eating from stress. Then pause."

  case identity = "Think: what would someone like me do right now?"
  case teaTrick = "Herbal tea with a strong flavour can scratch the snacking itch."
  case bananaBread = "Bake something healthier — it satisfies the ritual."
  case singleServe = "Portion out your snack instead of eating from the bag."
  case treatJar = "Have a treat jar. When it’s gone, it’s gone."
  case darkChocolate = "Dark chocolate. One square. Trust us."
  case appleCrunch = "Crunchy apples feel satisfying and take time to eat."
  case yoghurt = "Yoghurt and berries: sweet, filling, and protein-rich."
  case dontPunish = "Slipped up? Don’t punish yourself. That leads to spirals."
  case shareIt = "Want the snack? Offer to share it with someone."

  case visualise = "Picture yourself saying no — it makes it easier next time."
  case keepBusy = "Idle hands snack. Keep your hands busy."
  case putItAway = "Don’t leave it out. Out of sight, out of mouth."
  case sugarCrash = "Cravings often follow sugar crashes. Watch your meals."
  case rinse = "Rinse your mouth with mouthwash — it’s a hard reset."
  case music = "Play a song. By the end of it, your craving might be gone."
  case askWhy = "Ask yourself: why do I want this? The answer might surprise you."
  case freezeIt = "Freeze treats. You’ll think twice before defrosting."
  case logIt = "Log what you eat — accountability helps."
  case breakHabit = "Change the location. If you always snack at your desk, move."

  case snackBuddy = "Get a snack buddy. Someone to text when cravings hit."
  case smellCandle = "Scented candle trick: engage a different sense."
  case preCommit = "Tell someone your goal. It makes you stick to it."
  case visualGoal = "Stick a post-it with your goal on the fridge."
  case swapRitual = "Swap a snack-time ritual with a new one — like stretching."
  case playGame = "Open a game for 5 minutes instead of a snack drawer."
  case podcast = "Queue a podcast and go for a 10-min walk instead."
  case mirrorTalk = "Look in the mirror and say: 'Do I *really* want this?'"
  case barkMode = "Pretend you're Morsel. Would Morsel give in? Nah."
  case lightExercise = "20 jumping jacks kills a craving and gives you endorphins."

  case prepSnack = "Prep healthy snacks ahead of time — you'll thank yourself later."
  case eatEarlier = "Don’t skip meals — it backfires with late-night binges."
  case hungerScale = "Rate your hunger from 1–10 before snacking."
  case cleanUp = "Clean a small area instead — it's oddly satisfying."
  case petTime = "Pet your cat/dog/imaginary hedgehog. That works too."
  case postSnackPlan = "Have a post-snack rule: drink water + pause 10 mins."
  case gratitude = "Think of 3 things you're grateful for before opening the cupboard."
  case minty = "Minty things reduce appetite. Keep mints around."
  case fakeOrder = "Pretend you’re ordering delivery. Would you *actually* pay for this snack?"
  case standUp = "Stand up and stretch. Posture affects decisions too."

  case fiveMinuteRule = "Five-minute rule: wait, breathe, decide."
  case snackBox = "Make a snack box. One box. Once a day. That's it."
  case writeGoal = "Write your weekly goal on a sticky note and stick it somewhere visible."
  case themeWeek = "Have a theme week: fruit focus, hydration hero, etc."
  case drinkBeforeSnack = "Drink something warm before reaching for a snack."
  case eatWithHands = "Eat with your non-dominant hand to slow yourself down."
  case setTimer = "Set a timer for 10 mins. If you still want it, go ahead."
  case snackTrade = "Trade a snack for a walk or song — that counts."
  case celebrate = "Celebrate wins. Every resisted craving is a rep for your brain."
  case eveningWalk = "A 10-minute evening walk clears mind and stomach."

  case dontStockpile = "Don’t hoard snacks. You’re not a squirrel."
  case freshAir = "Go outside. Cravings hate fresh air."
  case messageAFriend = "Text a friend instead of snacking. You'll both win."
  case smellCoffee = "Smell coffee. Weirdly satisfying and 0 calories."
  case coldWater = "Cold water wakes you up *and* suppresses appetite."
  case countToTen = "Count to ten slowly before you open the snack drawer."
  case reframe = "Reframe it: 'I don’t' beats 'I can’t'."
  case tidySpace = "Tidy up your snack zone. Make it less tempting."
  case draw = "Draw something silly. You’ll forget the craving."
  case snackLess = "You don't need to snack every day. Challenge that belief."
}
