name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 26
        run: |
          sudo xcode-select -s /Applications/Xcode_26_beta.app/Contents/Developer
      - name: Install iOS 26 SDK
        run: |
          xcodebuild -downloadPlatform iOS
      - name: Prepare iOS Simulator
        run: |
          sudo xcodebuild -runFirstLaunch
      - name: Run Test Plan
        run: |
          xcodebuild test \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16e'