---
name: CI

'on':
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            | xcbeautify
