name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 26
        run: |
          sudo xcode-select -s /Applications/Xcode_26_beta.app/Contents/Developer

      - name: Cache iOS Simulator
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/CoreSimulator/Profiles/Runtimes
          key: ios-sim-26-23A5260l

      - name: Cache watchOS Simulator
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/CoreSimulator/Profiles/Runtimes
          key: watch-sim-26-23A5260l

      - name: Install iOS 26 SDK
        run: |
          xcodebuild -downloadPlatform iOS

      - name: Install watchOS 26 SDK
        run: |
          xcodebuild -downloadPlatform watchOS

      - name: Prepare iOS Simulator
        run: |
          sudo xcodebuild -runFirstLaunch

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run Test Plan
        run: |
          set -o pipefail
          xcodebuild test \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16e' \
            -resultBundlePath TestResults.xcresult | xcbeautify