name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Prefer stable Xcode 16 if available on the image
          xcode-version: '16.0'

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run Test Plan
        run: |
          set -o pipefail
          xcodebuild test \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' \
            -resultBundlePath TestResults.xcresult | xcbeautify
