---
name: CI

'on':
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Select Xcode
        run: xcodes list

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26_beta_6.app/Contents/Developer  

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            | xcbeautify
