name: Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run Test Plan
        run: |
          xcodebuild test \
            -workspace Morsel.xcworkspace \
            -scheme iOS \
            -destination 'platform=iOS Simulator,OS=18.6,name=iPhone 16e'
