name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Run unit tests
        run: |
          xcodebuild test \
            -project Morsel.xcodeproj \
            -scheme iOS \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            CODE_SIGNING_ALLOWED=NO

