name: Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.app/Contents/Developer
      - name: Install iOS 26 simulator
        run: sudo xcodebuild -downloadPlatform iOS
      - name: Install watchOS 11 simulator
        run: sudo xcodebuild -downloadPlatform watchOS
      - name: Run Core tests
        run: |
          xcodebuild test \
            -project Morsel.xcodeproj \
            -scheme CoreTests \
            -destination 'platform=iOS Simulator,OS=26.0,name=iPhone 16e'
      - name: Run iOS tests
        run: |
          xcodebuild test \
            -project Morsel.xcodeproj \
            -scheme iOS \
            -destination 'platform=iOS Simulator,OS=26.0,name=iPhone 16e'
      - name: Run watchOS tests
        run: |
          xcodebuild test \
            -project Morsel.xcodeproj \
            -scheme watchOS \
            -destination 'platform=watchOS Simulator,OS=11.0,name=Apple Watch Series 9 (45mm)'
